// <auto-generated />
using EntityFrameworkRelationshipsTesting;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkRelationshipsTesting.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201012201646_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkRelationshipsTesting.Entities.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Name = "Mailo"
                        },
                        new
                        {
                            DogId = 2,
                            Name = "Lilo"
                        },
                        new
                        {
                            DogId = 3,
                            Name = "Szarlo"
                        },
                        new
                        {
                            DogId = 4,
                            Name = "Izka"
                        });
                });

            modelBuilder.Entity("EntityFrameworkRelationshipsTesting.Entities.DogBreeder", b =>
                {
                    b.Property<int>("DogBreederId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DogBreederId");

                    b.HasIndex("DogId")
                        .IsUnique();

                    b.ToTable("DogBreeders");
                });

            modelBuilder.Entity("EntityFrameworkRelationshipsTesting.Entities.DogOwner", b =>
                {
                    b.Property<int>("DogOwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DogOwnerId");

                    b.ToTable("DogOwners");
                });

            modelBuilder.Entity("EntityFrameworkRelationshipsTesting.Entities.DogOwnerDog", b =>
                {
                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<int>("DogOwnerId")
                        .HasColumnType("int");

                    b.HasKey("DogId", "DogOwnerId");

                    b.HasIndex("DogOwnerId");

                    b.ToTable("DogOwnerDogs");
                });

            modelBuilder.Entity("EntityFrameworkRelationshipsTesting.Entities.Puppy", b =>
                {
                    b.Property<int>("PuppyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PuppyId");

                    b.HasIndex("DogId");

                    b.ToTable("Puppies");

                    b.HasData(
                        new
                        {
                            PuppyId = 1,
                            DogId = 1,
                            Name = "Mailo1"
                        },
                        new
                        {
                            PuppyId = 2,
                            DogId = 1,
                            Name = "Mailo2"
                        },
                        new
                        {
                            PuppyId = 3,
                            DogId = 2,
                            Name = "Lilo1"
                        },
                        new
                        {
                            PuppyId = 4,
                            DogId = 2,
                            Name = "Lilo2"
                        },
                        new
                        {
                            PuppyId = 5,
                            DogId = 2,
                            Name = "Lilo3"
                        },
                        new
                        {
                            PuppyId = 6,
                            DogId = 3,
                            Name = "Szarlo1"
                        },
                        new
                        {
                            PuppyId = 7,
                            DogId = 3,
                            Name = "Szarlo2"
                        },
                        new
                        {
                            PuppyId = 8,
                            DogId = 3,
                            Name = "Szarlo3"
                        });
                });

            modelBuilder.Entity("EntityFrameworkRelationshipsTesting.Entities.DogBreeder", b =>
                {
                    b.HasOne("EntityFrameworkRelationshipsTesting.Entities.Dog", null)
                        .WithOne("DogBreeder")
                        .HasForeignKey("EntityFrameworkRelationshipsTesting.Entities.DogBreeder", "DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkRelationshipsTesting.Entities.DogOwnerDog", b =>
                {
                    b.HasOne("EntityFrameworkRelationshipsTesting.Entities.Dog", "Dog")
                        .WithMany("DogOwnerDogs")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameworkRelationshipsTesting.Entities.DogOwner", "DogOwner")
                        .WithMany("DogOwnerDogs")
                        .HasForeignKey("DogOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkRelationshipsTesting.Entities.Puppy", b =>
                {
                    b.HasOne("EntityFrameworkRelationshipsTesting.Entities.Dog", "Dog")
                        .WithMany("Puppies")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
