// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dogdata {

  /// <summary>Holder for reflection information generated from message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1tZXNzYWdlLnByb3RvEgdkb2dkYXRhGhlnb29nbGUvcHJvdG9idWYvYW55",
            "LnByb3RvGg1hZGRyZXNzLnByb3RvGgp0eXBlLnByb3RvIsgCCghDdXN0b21l",
            "chIQCgh1c2VybmFtZRgBIAEoCRIpCg9lbWFpbF9hZGRyZXNzZXMYAiADKAsy",
            "EC5kb2dkYXRhLkFkZHJlc3MSIQoEdHlwZRgDIAEoDjITLmRvZ2RhdGEuQ3Vz",
            "dG9tVHlwZRIOCgRuYW1lGAQgASgJSAASDwoFbmFtZTIYBSABKAlIABI2Cgth",
            "bmltYWxfZm9vZBgGIAMoCzIhLmRvZ2RhdGEuQ3VzdG9tZXIuQW5pbWFsRm9v",
            "ZEVudHJ5EjMKEG5vX2RpZmZyZW50X3doYXQYByABKAsyFC5nb29nbGUucHJv",
            "dG9idWYuQW55SAGIAQEaMQoPQW5pbWFsRm9vZEVudHJ5EgsKA2tleRgBIAEo",
            "BRINCgV2YWx1ZRgCIAEoCToCOAFCBgoEdGVzdEITChFfbm9fZGlmZnJlbnRf",
            "d2hhdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::Dogdata.AddressReflection.Descriptor, global::Dogdata.TypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dogdata.Customer), global::Dogdata.Customer.Parser, new[]{ "Username", "EmailAddresses", "Type", "Name", "Name2", "AnimalFood", "NoDiffrentWhat" }, new[]{ "Test", "NoDiffrentWhat" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Customer : pb::IMessage<Customer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Customer> _parser = new pb::MessageParser<Customer>(() => new Customer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Customer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dogdata.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Customer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Customer(Customer other) : this() {
      username_ = other.username_;
      emailAddresses_ = other.emailAddresses_.Clone();
      type_ = other.type_;
      animalFood_ = other.animalFood_.Clone();
      noDiffrentWhat_ = other.noDiffrentWhat_ != null ? other.noDiffrentWhat_.Clone() : null;
      switch (other.TestCase) {
        case TestOneofCase.Name:
          Name = other.Name;
          break;
        case TestOneofCase.Name2:
          Name2 = other.Name2;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Customer Clone() {
      return new Customer(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email_addresses" field.</summary>
    public const int EmailAddressesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Dogdata.Address> _repeated_emailAddresses_codec
        = pb::FieldCodec.ForMessage(18, global::Dogdata.Address.Parser);
    private readonly pbc::RepeatedField<global::Dogdata.Address> emailAddresses_ = new pbc::RepeatedField<global::Dogdata.Address>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Dogdata.Address> EmailAddresses {
      get { return emailAddresses_; }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 3;
    private global::Dogdata.CustomType type_ = global::Dogdata.CustomType.Roar;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dogdata.CustomType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return testCase_ == TestOneofCase.Name ? (string) test_ : ""; }
      set {
        test_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        testCase_ = TestOneofCase.Name;
      }
    }

    /// <summary>Field number for the "name2" field.</summary>
    public const int Name2FieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name2 {
      get { return testCase_ == TestOneofCase.Name2 ? (string) test_ : ""; }
      set {
        test_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        testCase_ = TestOneofCase.Name2;
      }
    }

    /// <summary>Field number for the "animal_food" field.</summary>
    public const int AnimalFoodFieldNumber = 6;
    private static readonly pbc::MapField<int, string>.Codec _map_animalFood_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForString(18, ""), 50);
    private readonly pbc::MapField<int, string> animalFood_ = new pbc::MapField<int, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, string> AnimalFood {
      get { return animalFood_; }
    }

    /// <summary>Field number for the "no_diffrent_what" field.</summary>
    public const int NoDiffrentWhatFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Any noDiffrentWhat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any NoDiffrentWhat {
      get { return noDiffrentWhat_; }
      set {
        noDiffrentWhat_ = value;
      }
    }

    private object test_;
    /// <summary>Enum of possible cases for the "test" oneof.</summary>
    public enum TestOneofCase {
      None = 0,
      Name = 4,
      Name2 = 5,
    }
    private TestOneofCase testCase_ = TestOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestOneofCase TestCase {
      get { return testCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTest() {
      testCase_ = TestOneofCase.None;
      test_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Customer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Customer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if(!emailAddresses_.Equals(other.emailAddresses_)) return false;
      if (Type != other.Type) return false;
      if (Name != other.Name) return false;
      if (Name2 != other.Name2) return false;
      if (!AnimalFood.Equals(other.AnimalFood)) return false;
      if (!object.Equals(NoDiffrentWhat, other.NoDiffrentWhat)) return false;
      if (TestCase != other.TestCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      hash ^= emailAddresses_.GetHashCode();
      if (Type != global::Dogdata.CustomType.Roar) hash ^= Type.GetHashCode();
      if (testCase_ == TestOneofCase.Name) hash ^= Name.GetHashCode();
      if (testCase_ == TestOneofCase.Name2) hash ^= Name2.GetHashCode();
      hash ^= AnimalFood.GetHashCode();
      if (noDiffrentWhat_ != null) hash ^= NoDiffrentWhat.GetHashCode();
      hash ^= (int) testCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      emailAddresses_.WriteTo(output, _repeated_emailAddresses_codec);
      if (Type != global::Dogdata.CustomType.Roar) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
      if (testCase_ == TestOneofCase.Name) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (testCase_ == TestOneofCase.Name2) {
        output.WriteRawTag(42);
        output.WriteString(Name2);
      }
      animalFood_.WriteTo(output, _map_animalFood_codec);
      if (noDiffrentWhat_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(NoDiffrentWhat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      emailAddresses_.WriteTo(ref output, _repeated_emailAddresses_codec);
      if (Type != global::Dogdata.CustomType.Roar) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
      if (testCase_ == TestOneofCase.Name) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (testCase_ == TestOneofCase.Name2) {
        output.WriteRawTag(42);
        output.WriteString(Name2);
      }
      animalFood_.WriteTo(ref output, _map_animalFood_codec);
      if (noDiffrentWhat_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(NoDiffrentWhat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      size += emailAddresses_.CalculateSize(_repeated_emailAddresses_codec);
      if (Type != global::Dogdata.CustomType.Roar) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (testCase_ == TestOneofCase.Name) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (testCase_ == TestOneofCase.Name2) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name2);
      }
      size += animalFood_.CalculateSize(_map_animalFood_codec);
      if (noDiffrentWhat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NoDiffrentWhat);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Customer other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      emailAddresses_.Add(other.emailAddresses_);
      if (other.Type != global::Dogdata.CustomType.Roar) {
        Type = other.Type;
      }
      animalFood_.Add(other.animalFood_);
      if (other.noDiffrentWhat_ != null) {
        if (noDiffrentWhat_ == null) {
          NoDiffrentWhat = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        NoDiffrentWhat.MergeFrom(other.NoDiffrentWhat);
      }
      switch (other.TestCase) {
        case TestOneofCase.Name:
          Name = other.Name;
          break;
        case TestOneofCase.Name2:
          Name2 = other.Name2;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            emailAddresses_.AddEntriesFrom(input, _repeated_emailAddresses_codec);
            break;
          }
          case 24: {
            Type = (global::Dogdata.CustomType) input.ReadEnum();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 42: {
            Name2 = input.ReadString();
            break;
          }
          case 50: {
            animalFood_.AddEntriesFrom(input, _map_animalFood_codec);
            break;
          }
          case 58: {
            if (noDiffrentWhat_ == null) {
              NoDiffrentWhat = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(NoDiffrentWhat);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            emailAddresses_.AddEntriesFrom(ref input, _repeated_emailAddresses_codec);
            break;
          }
          case 24: {
            Type = (global::Dogdata.CustomType) input.ReadEnum();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 42: {
            Name2 = input.ReadString();
            break;
          }
          case 50: {
            animalFood_.AddEntriesFrom(ref input, _map_animalFood_codec);
            break;
          }
          case 58: {
            if (noDiffrentWhat_ == null) {
              NoDiffrentWhat = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(NoDiffrentWhat);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
