// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dogdata {

  /// <summary>Holder for reflection information generated from type.proto</summary>
  public static partial class TypeReflection {

    #region Descriptor
    /// <summary>File descriptor for type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgp0eXBlLnByb3RvEgdkb2dkYXRhKigKCkN1c3RvbVR5cGUSCAoEUk9BUhAA",
            "EgcKA0RPRxABEgcKA0NBVBACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Dogdata.CustomType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CustomType {
    [pbr::OriginalName("ROAR")] Roar = 0,
    [pbr::OriginalName("DOG")] Dog = 1,
    [pbr::OriginalName("CAT")] Cat = 2,
  }

  #endregion

}

#endregion Designer generated code
