# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherAppWithStoryboard' do
  pod 'Alamofire', '~> 4.5'
  
  pod 'Toast-Swift', '~> 5.0.1'

end
