//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalInfomationWebService.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PeopleDbEntities : DbContext
    {
        public PeopleDbEntities()
            : base("name=PeopleDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GENDERS> GENDERS { get; set; }
        public virtual DbSet<PEOPLE> PEOPLE { get; set; }
    
        public virtual int ADD_NEW_PERSON(string nAME, string sURNAME, string gENDER)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var sURNAMEParameter = sURNAME != null ?
                new ObjectParameter("SURNAME", sURNAME) :
                new ObjectParameter("SURNAME", typeof(string));
    
            var gENDERParameter = gENDER != null ?
                new ObjectParameter("GENDER", gENDER) :
                new ObjectParameter("GENDER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_NEW_PERSON", nAMEParameter, sURNAMEParameter, gENDERParameter);
        }
    }
}
